/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arjun.allwordplays;

import arjun.guesswho.GuessWho;
import arjun.vocabulary.Vocabulary;
import arjun.wordladdersolver.WordLadderSolverUI;
import arjun.wordscramble.WordScrambleUI;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Arjun
 */
public class WordPlaysUI extends javax.swing.JFrame {
    private static String[] m_Args = null;

    /**
     * Creates new form WordPlaysUI
     */
    public WordPlaysUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuessWhoButton = new javax.swing.JButton();
        VocabularyButton = new javax.swing.JButton();
        WordScrambleButton = new javax.swing.JButton();
        WordLadderSolverButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WORD PLAY");

        GuessWhoButton.setText("PLAY GUESS WHO?");
        GuessWhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuessWhoButtonActionPerformed(evt);
            }
        });

        VocabularyButton.setText("PLAY VOCABULARY!");
        VocabularyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VocabularyButtonActionPerformed(evt);
            }
        });

        WordScrambleButton.setText("PLAY WORD SCRAMBLE");
        WordScrambleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WordScrambleButtonActionPerformed(evt);
            }
        });

        WordLadderSolverButton.setText("RUN WORD LADDER SOLVER");
        WordLadderSolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WordLadderSolverButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Word Play");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Resource for Word Games & Solvers");

        AboutButton.setText("ABOUT");
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(35, 35, 35)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(WordLadderSolverButton)
                                    .add(VocabularyButton)
                                    .add(WordScrambleButton))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(GuessWhoButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(AboutButton)
                                .add(31, 31, 31))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(8, 8, 8)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(GuessWhoButton)
                    .add(AboutButton))
                .add(27, 27, 27)
                .add(VocabularyButton)
                .add(34, 34, 34)
                .add(WordScrambleButton)
                .add(35, 35, 35)
                .add(WordLadderSolverButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuessWhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuessWhoButtonActionPerformed
        GuessWho.mainApp(m_Args);
    }//GEN-LAST:event_GuessWhoButtonActionPerformed

    private void VocabularyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VocabularyButtonActionPerformed
        try {
            Vocabulary.mainApp(m_Args);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WordPlaysUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VocabularyButtonActionPerformed

    private void WordScrambleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WordScrambleButtonActionPerformed
        WordScrambleUI.mainApp(m_Args);
    }//GEN-LAST:event_WordScrambleButtonActionPerformed

    private void WordLadderSolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WordLadderSolverButtonActionPerformed
        WordLadderSolverUI.mainApp(m_Args);
    }//GEN-LAST:event_WordLadderSolverButtonActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Author: Arjun Banerjee\nYear: 2014\nAll Copyrights Reserved", "ABOUT Word Play", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AboutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordPlaysUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordPlaysUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordPlaysUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordPlaysUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Save args into m_Args */
        if (args != null) {
            m_Args = new String [args.length];
            for (int i = 0; i < args.length; i++) {
                m_Args[i] = args[i];
            }
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordPlaysUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton GuessWhoButton;
    private javax.swing.JButton VocabularyButton;
    private javax.swing.JButton WordLadderSolverButton;
    private javax.swing.JButton WordScrambleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
